
const allocation = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [
          {
            label: '制单',
            value: 'allocation_create'
          }, {
            label: '等待出库',
            value: 'allocation_wait_out'
          }, {
            label: '出库中',
            value: 'allocation_out_ing'
          }, {
            label: '调拨中',
            value: 'allocation_ing'
          }, {
            label: '入库中',
            value: 'allocation_in_ing'
          }, {
            label: '归档',
            value: 'allocation_doc'
          }
        ]
      }, {
        title: "调拨单号",
        dataKey: "allocationCode",
        key: 'allocationCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库名称",
        dataKey: "toWarehouseName",
        key: 'toWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "提库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "调拨总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "调拨总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "验货人",
        dataKey: "pickingMan",
        key: 'pickingMan',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "调拨单打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [
          {
            label: '制单',
            value: 'allocation_create'
          }, {
            label: '等待出库',
            value: 'allocation_wait_out'
          }, {
            label: '出库中',
            value: 'allocation_out_ing'
          }, {
            label: '调拨中',
            value: 'allocation_ing'
          }, {
            label: '入库中',
            value: 'allocation_in_ing'
          }, {
            label: '归档',
            value: 'allocation_doc'
          }
        ]
      }, {
        title: "调拨单号",
        dataKey: "allocationCode",
        key: 'allocationCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库名称",
        dataKey: "toWarehouseName",
        key: 'toWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "提库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "调拨总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "调拨总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "验货人",
        dataKey: "pickingMan",
        key: 'pickingMan',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "调拨单打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default allocation
