
const batch = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "批次号",
        dataKey: "batchCode",
        key: 'batchCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类别名称",
        dataKey: "categoryName",
        key: 'categoryName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库时间",
        dataKey: "inTime",
        key: 'inTime',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "初始量",
        dataKey: "number",
        key: 'number',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "现有量",
        dataKey: "nowNumber",
        key: 'nowNumber',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "批次号",
        dataKey: "batchCode",
        key: 'batchCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类别名称",
        dataKey: "categoryName",
        key: 'categoryName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库时间",
        dataKey: "inTime",
        key: 'inTime',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "初始量",
        dataKey: "number",
        key: 'number',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "现有量",
        dataKey: "nowNumber",
        key: 'nowNumber',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default batch
