
const checkWorks = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '未盘点',
          value: 'inventory_task_allocation_not_started'
        }, {
          label: '盘点完成',
          value: 'inventory_task_allocation_end'
        }, {
          label: '待复盘',
          value: 'inventory_task_allocation_reviewed'
        }]
      }, {
        title: "盘点工作单号",
        dataKey: "inventoryTaskOrderCode",
        key: 'inventoryTaskOrderCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点工作名称",
        dataKey: "inventoryTaskName",
        key: 'inventoryTaskName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点类型",
        dataKey: "inventoryType",
        key: 'inventoryType',
        width: 200,
        type: 'options',
        isShow: true,
        isFixed: false,
        options: [{
          label: '仓位',
          value: 'CW'
        }, {
          label: '产品',
          value: `WL`
        }]
      }, {
        title: "盘点工作日期",
        dataKey: "inventoryTaskDate",
        key: 'inventoryTaskDate',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点人",
        dataKey: "inventoryUserName",
        key: 'inventoryUserName',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "明盘/暗盘",
        dataKey: "isOpenCheck",
        key: 'isOpenCheck',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '暗盘',
          value: 2
        }, {
          label: '明盘',
          value: 1
        }]
      }, {
        title: "盈亏总数量",
        dataKey: "profitAndLossQuantitySum",
        key: 'profitAndLossQuantitySum',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '未盘点',
          value: 'inventory_task_allocation_not_started'
        }, {
          label: '盘点完成',
          value: 'inventory_task_allocation_end'
        }, {
          label: '待复盘',
          value: 'inventory_task_allocation_reviewed'
        }]
      }, {
        title: "盘点工作单号",
        dataKey: "inventoryTaskOrderCode",
        key: 'inventoryTaskOrderCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点工作名称",
        dataKey: "inventoryTaskName",
        key: 'inventoryTaskName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点类型",
        dataKey: "inventoryType",
        key: 'inventoryType',
        width: 200,
        type: 'options',
        isShow: true,
        isFixed: false,
        options: [{
          label: '仓位',
          value: 'CW'
        }, {
          label: '产品',
          value: `WL`
        }]
      }, {
        title: "盘点工作日期",
        dataKey: "inventoryTaskDate",
        key: 'inventoryTaskDate',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点人",
        dataKey: "inventoryUserName",
        key: 'inventoryUserName',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "明盘/暗盘",
        dataKey: "isOpenCheck",
        key: 'isOpenCheck',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '暗盘',
          value: 2
        }, {
          label: '明盘',
          value: 1
        }]
      }, {
        title: "盈亏总数量",
        dataKey: "profitAndLossQuantitySum",
        key: 'profitAndLossQuantitySum',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default checkWorks
