
const checkMissions = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '制单',
          value: 'inventory_task_create'
        }, {
          label: '盘点中',
          value: 'inventory_task_start'
        }, {
          label: '审核',
          value: 'inventory_task_audit'
        }, {
          label: '归档',
          value: 'inventory_task_doc'
        }]
      }, {
        title: "盘点任务单号",
        dataKey: "inventoryTaskOrderCode",
        key: 'inventoryTaskOrderCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务名称",
        dataKey: "inventoryTaskName",
        key: 'inventoryTaskName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点类型",
        dataKey: "inventoryType",
        key: 'inventoryType',
        width: 200,
        type: 'options',
        isShow: true,
        isFixed: false,
        options: [{
          label: '仓位',
          value: 'CW'
        }, {
          label: '产品',
          value: `WL`
        }]
      }, {
        title: "盘点仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务日期",
        dataKey: "inventoryTaskDate",
        key: 'inventoryTaskDate',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "明盘/暗盘",
        dataKey: "isOpenCheck",
        key: 'isOpenCheck',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '暗盘',
          value: 2
        }, {
          label: '明盘',
          value: 1
        }]
      }, {
        title: "盈亏总数量",
        dataKey: "profitAndLossQuantitySum",
        key: 'profitAndLossQuantitySum',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "盘对人员",
        dataKey: "userObject",
        key: 'userObject',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '制单',
          value: 'inventory_task_create'
        }, {
          label: '盘点中',
          value: 'inventory_task_start'
        }, {
          label: '审核',
          value: 'inventory_task_audit'
        }, {
          label: '归档',
          value: 'inventory_task_doc'
        }]
      }, {
        title: "盘点任务单号",
        dataKey: "inventoryTaskOrderCode",
        key: 'inventoryTaskOrderCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务名称",
        dataKey: "inventoryTaskName",
        key: 'inventoryTaskName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点类型",
        dataKey: "inventoryType",
        key: 'inventoryType',
        width: 200,
        type: 'options',
        isShow: true,
        isFixed: false,
        options: [{
          label: '仓位',
          value: 'CW'
        }, {
          label: '产品',
          value: `WL`
        }]
      }, {
        title: "盘点仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务日期",
        dataKey: "inventoryTaskDate",
        key: 'inventoryTaskDate',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "明盘/暗盘",
        dataKey: "isOpenCheck",
        key: 'isOpenCheck',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '暗盘',
          value: 2
        }, {
          label: '明盘',
          value: 1
        }]
      }, {
        title: "盈亏总数量",
        dataKey: "profitAndLossQuantitySum",
        key: 'profitAndLossQuantitySum',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "盘对人员",
        dataKey: "userObject",
        key: 'userObject',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default checkMissions
