
const out = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [
          {
            label: '制单',
            value: 'in_create'
          }, {
            label: '等待出库',
            value: 'in_wait_out'
          }, {
            label: '出库中',
            value: 'in_ing'
          }, {
            label: '归档',
            value: 'in_doc'
          }, {
            label: '作废',
            value: 'in_cancel'
          }
        ]
      }, {
        title: "入库单号",
        dataKey: "inWarehouseCode",
        key: 'inWarehouseCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "入库单类型",
        dataKey: "type",
        key: 'type',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: []
      }, {
        title: "入库关联商家",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "提库名称",
        dataKey: "pickUpWarehouse",
        key: 'pickUpWarehouse',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "入库总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "验货人",
        dataKey: "inspectionPerson",
        key: 'inspectionPerson',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库单打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [
          {
            label: '制单',
            value: 'in_create'
          }, {
            label: '等待出库',
            value: 'in_wait_out'
          }, {
            label: '出库中',
            value: 'in_ing'
          }, {
            label: '归档',
            value: 'in_doc'
          }, {
            label: '作废',
            value: 'in_cancel'
          }
        ]
      }, {
        title: "入库单号",
        dataKey: "inWarehouseCode",
        key: 'inWarehouseCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "入库单类型",
        dataKey: "type",
        key: 'type',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: []
      }, {
        title: "入库关联商家",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "提库名称",
        dataKey: "pickUpWarehouse",
        key: 'pickUpWarehouse',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "入库总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "验货人",
        dataKey: "inspectionPerson",
        key: 'inspectionPerson',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "入库单打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default out
