
const out = {
  namespaced: true,
  state: {
    tableHeader: [
      { //出库单流程状态

        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [
          {
            label: '制单',
            value: 'out_create'
          }, {
            label: '等待出库',
            value: 'out_wait_out'
          }, {
            label: '出库中',
            value: 'out_out_ing'
          }, {
            label: '归档',
            value: 'out_doc'
          }, {
            label: '作废',
            value: 'out_cancel'
          }
        ]
      }, {
        title: "出库单号",
        dataKey: "outWarehouseCode",
        key: 'outWarehouseCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "出库单类型",
        dataKey: "type",
        key: 'type',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '普通出库',
          value: '普通出库'
        }, {
          label: '调拨出库',
          value: '调拨出库'
        }]
      }, {
        title: "仓库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "出库总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "出库总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "出库关联单号",
        dataKey: "saleAllCodes",
        key: 'saleAllCodes',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "出库关联商家",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "出库单打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      { //出库单流程状态

        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [
          {
            label: '制单',
            value: 'out_create'
          }, {
            label: '等待出库',
            value: 'out_wait_out'
          }, {
            label: '出库中',
            value: 'out_out_ing'
          }, {
            label: '归档',
            value: 'out_doc'
          }, {
            label: '作废',
            value: 'out_cancel'
          }
        ]
      }, {
        title: "出库单号",
        dataKey: "outWarehouseCode",
        key: 'outWarehouseCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "出库单类型",
        dataKey: "type",
        key: 'type',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '普通出库',
          value: '普通出库'
        }, {
          label: '调拨出库',
          value: '调拨出库'
        }]
      }, {
        title: "仓库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "出库总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "出库总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "出库关联单号",
        dataKey: "saleAllCodes",
        key: 'saleAllCodes',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "出库关联商家",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "出库单打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default out
