
const position = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓位名称",
        dataKey: "positionName",
        key: 'positionName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "总数量",
        dataKey: "sumNum",
        key: 'sumNum',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "冻结数量",
        dataKey: "frozenNum",
        key: 'frozenNum',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库类型",
        dataKey: "warehouseType",
        key: 'warehouseType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: true,
        options: [{
          label: '仓库',
          value: 'warehouse'
        }, {
          label: '库区',
          value: 'area'
        }, {
          label: '货架',
          value: 'frame'
        }, {
          label: '仓位',
          value: 'position'
        }]
      }, {
        title: "产品类型",
        dataKey: "productType",
        key: 'productType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          value: '组合',
          label: '组合'
        }, {
          value: '单件',
          label: '单件'
        }]
      }, {
        title: "产品型号",
        dataKey: "productSpecification",
        key: 'productSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品单位",
        dataKey: "productUnit",
        key: 'productUnit',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "产品条码",
        dataKey: "barCode",
        key: 'barCode',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "是否冻结",
        dataKey: "isFrozen",
        key: 'isFrozen',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓位名称",
        dataKey: "positionName",
        key: 'positionName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "总数量",
        dataKey: "sumNum",
        key: 'sumNum',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "冻结数量",
        dataKey: "frozenNum",
        key: 'frozenNum',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库类型",
        dataKey: "warehouseType",
        key: 'warehouseType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: true,
        options: [{
          label: '仓库',
          value: 'warehouse'
        }, {
          label: '库区',
          value: 'area'
        }, {
          label: '货架',
          value: 'frame'
        }, {
          label: '仓位',
          value: 'position'
        }]
      }, {
        title: "产品类型",
        dataKey: "productType",
        key: 'productType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          value: '组合',
          label: '组合'
        }, {
          value: '单件',
          label: '单件'
        }]
      }, {
        title: "产品型号",
        dataKey: "productSpecification",
        key: 'productSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品单位",
        dataKey: "productUnit",
        key: 'productUnit',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "产品条码",
        dataKey: "barCode",
        key: 'barCode',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "是否冻结",
        dataKey: "isFrozen",
        key: 'isFrozen',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default position
