
const product = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类型",
        dataKey: "productType",
        key: 'productType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          value: '组合',
          label: '组合'
        }, {
          value: '单件',
          label: '单件'
        }]
      },
      {
        title: "产品类别",
        dataKey: "categoryName",
        key: 'categoryName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品型号",
        dataKey: "productSpecification",
        key: 'productSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "是否统一条码",
        dataKey: "productBarcodeAlways",
        key: 'productBarcodeAlways',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "条码头",
        dataKey: "barCodeHead",
        key: 'barCodeHead',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "品牌",
        dataKey: "brand",
        key: 'brand',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "单位",
        dataKey: "unit",
        key: 'unit',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "重量/KG",
        dataKey: "weight",
        key: 'weight',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "体积/L",
        dataKey: "volume",
        key: 'volume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "长/宽/高(m)",
        dataKey: "length",
        key: 'length',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类型",
        dataKey: "productType",
        key: 'productType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          value: '组合',
          label: '组合'
        }, {
          value: '单件',
          label: '单件'
        }]
      },
      {
        title: "产品类别",
        dataKey: "categoryName",
        key: 'categoryName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品型号",
        dataKey: "productSpecification",
        key: 'productSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "是否统一条码",
        dataKey: "productBarcodeAlways",
        key: 'productBarcodeAlways',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "条码头",
        dataKey: "barCodeHead",
        key: 'barCodeHead',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "品牌",
        dataKey: "brand",
        key: 'brand',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "单位",
        dataKey: "unit",
        key: 'unit',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "重量/KG",
        dataKey: "weight",
        key: 'weight',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "体积/L",
        dataKey: "volume",
        key: 'volume',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "长/宽/高(m)",
        dataKey: "length",
        key: 'length',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default product
