
const shoper = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "登录账号",
        dataKey: "accountId",
        key: 'accountId',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "简称",
        dataKey: "merchantShortName",
        key: 'merchantShortName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "负责人",
        dataKey: "merchantLinkman",
        key: 'merchantLinkman',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "负责人电话",
        dataKey: "merchantLinkmanPhone",
        key: 'merchantLinkmanPhone',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "省/市/区/街道",
        dataKey: "place",
        key: 'place',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "详细地址",
        dataKey: "storeAddress",
        key: 'storeAddress',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "电子邮箱",
        dataKey: "email",
        key: 'email',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "登录账号",
        dataKey: "accountId",
        key: 'accountId',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "简称",
        dataKey: "merchantShortName",
        key: 'merchantShortName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "负责人",
        dataKey: "merchantLinkman",
        key: 'merchantLinkman',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "负责人电话",
        dataKey: "merchantLinkmanPhone",
        key: 'merchantLinkmanPhone',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "省/市/区/街道",
        dataKey: "place",
        key: 'place',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "详细地址",
        dataKey: "storeAddress",
        key: 'storeAddress',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "电子邮箱",
        dataKey: "email",
        key: 'email',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default shoper
