
const stock = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品所在仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "现有量",
        dataKey: "nowNumber",
        key: 'nowNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "冻结量",
        dataKey: "frozenNumber",
        key: 'frozenNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "安全库存",
        dataKey: "safeNumber",
        key: 'safeNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "库存上限",
        dataKey: "excessNumber",
        key: 'excessNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类型",
        dataKey: "productType",
        key: 'productType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '组合',
          value: '组合'
        }, {
          label: '单件',
          value: '单件'
        }]
      }, {
        title: "产品型号",
        dataKey: "productSpecification",
        key: 'productSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品单位",
        dataKey: "productUnit",
        key: 'productUnit',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "产品代码",
        dataKey: "productCode",
        key: 'productCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品名称",
        dataKey: "productName",
        key: 'productName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品所在仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "现有量",
        dataKey: "nowNumber",
        key: 'nowNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "冻结量",
        dataKey: "frozenNumber",
        key: 'frozenNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "安全库存",
        dataKey: "safeNumber",
        key: 'safeNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "库存上限",
        dataKey: "excessNumber",
        key: 'excessNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类型",
        dataKey: "productType",
        key: 'productType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '组合',
          value: '组合'
        }, {
          label: '单件',
          value: '单件'
        }]
      }, {
        title: "产品型号",
        dataKey: "productSpecification",
        key: 'productSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品单位",
        dataKey: "productUnit",
        key: 'productUnit',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default stock
