
const warehouse = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "仓库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "仓库代码",
        dataKey: "warehouseCode",
        key: 'warehouseCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "仓库类型",
        dataKey: "warehouseType",
        key: 'warehouseType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: true,
        options: [{
          label: '仓库',
          value: 'warehouse'
        }, {
          label: '库区',
          value: 'area'
        }, {
          label: '货架',
          value: 'frame'
        }, {
          label: '仓位',
          value: 'position'
        }]
      }, {
        title: "仓库地址",
        dataKey: "warehouseAddress",
        key: 'warehouseAddress',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库负责人",
        dataKey: "warehouseKeeper",
        key: 'warehouseKeeper',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库联系电话",
        dataKey: "linkmanPhone",
        key: 'linkmanPhone',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "容量",
        dataKey: "capacity",
        key: 'capacity',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "地图地标",
        dataKey: "landmark",
        key: 'landmark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "经-纬度",
        dataKey: "latAndlong",
        key: 'latAndlong',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "规格(行*列)",
        dataKey: "positions",
        key: 'positions',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "仓库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "仓库代码",
        dataKey: "warehouseCode",
        key: 'warehouseCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: true
      }, {
        title: "仓库类型",
        dataKey: "warehouseType",
        key: 'warehouseType',
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: true,
        options: [{
          label: '仓库',
          value: 'warehouse'
        }, {
          label: '库区',
          value: 'area'
        }, {
          label: '货架',
          value: 'frame'
        }, {
          label: '仓位',
          value: 'position'
        }]
      }, {
        title: "仓库地址",
        dataKey: "warehouseAddress",
        key: 'warehouseAddress',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库负责人",
        dataKey: "warehouseKeeper",
        key: 'warehouseKeeper',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库联系电话",
        dataKey: "linkmanPhone",
        key: 'linkmanPhone',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "容量",
        dataKey: "capacity",
        key: 'capacity',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "地图地标",
        dataKey: "landmark",
        key: 'landmark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "经-纬度",
        dataKey: "latAndlong",
        key: 'latAndlong',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "规格(行*列)",
        dataKey: "positions",
        key: 'positions',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default warehouse
