
const worker = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "员工账号",
        dataKey: "accountId",
        key: 'accountId',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "员工名称",
        dataKey: "employeeName",
        key: 'employeeName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "员工电话",
        dataKey: "employeePhone",
        key: 'employeePhone',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "角色名称",
        dataKey: "employeeRoleName",
        key: 'employeeRoleName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "员工所属仓库",
        dataKey: "employeeWarehouseName",
        key: 'employeeWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "电子邮箱",
        dataKey: "email",
        key: 'email',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "员工账号",
        dataKey: "accountId",
        key: 'accountId',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "员工名称",
        dataKey: "employeeName",
        key: 'employeeName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "员工电话",
        dataKey: "employeePhone",
        key: 'employeePhone',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "角色名称",
        dataKey: "employeeRoleName",
        key: 'employeeRoleName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "员工所属仓库",
        dataKey: "employeeWarehouseName",
        key: 'employeeWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "电子邮箱",
        dataKey: "email",
        key: 'email',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "remark",
        key: 'remark',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建者",
        dataKey: "createBy",
        key: 'createBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新者",
        dataKey: "updateBy",
        key: 'updateBy',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default worker
